### ISSUE TITLE
Instructions unclear and Unexpected Results.

### ISSUE THREAD

**Issue by fxrstor** [joepigott/dots#3]
Hello,
I followed the instructions:
   1. Copy all the config directories to my `~/.config`
   2. Install `weather-text`. Placed my API key and the zip code listed in the example in the respective file. Tested it, works by displaying the temperature in Kelvin scale and "clear sky".
   3. Create wallpaper directory and copy mandelbrot wallpaper there.
   4. Install Terminus font because it's listed in `theme.lua`
   5. Started awesomewm through `startx`. My `.xinitrc` is just `"exec awesome"`. It displays errors in `bar.lua`. The weather and the notif thing was nil. I removed them to just try the dots as of now, later fix them. But when I started, it was no closer to the screenshot. It only had date and time on the bar and nothing else. No window management buttons (i.e. close, minimize, maximize). No effects.

What do you think? Is this the problem with the dots or the instructions? Or is it just me being dumb? Because I'm totally new to awesome community. I can provide screenshot and additional information upon request.

**Comment by joepigott** [comment]
I forgot to update the docs but it currently depends on the recent changes to AwesomeWM that haven't been merged into the stable packages. So if you're getting errors in `bar.lua` it's probably because of that. Try using `awesome-git` from the AUR or whatever the equivalent is for your distribution. If you still have issues then ping me here again, I'll see what I can do.

**Comment by fxrstor** [comment]
![image](https://github.com/user-attachments/assets/a790aa32-f7ba-4848-ae0d-6e79a151c71b)
Great. Everything works fine. There's a problem with the notif button, you can see that its improperly placed (notification bell), plus I've also decreased the `Font 26` to `Font 14` to make it smaller. Is there any way to perfectly place it in center? If no, I don't actually care because the difference is very minor and hardly noticeable.

There's one question, where do the minimized windows go? I'm new to the community, the keybinds are pretty strange. Mod + Shift + Q kills a window in bspwm (common keybind), but awesomewm it kills the wm itself.

**Comment by joepigott** [comment]
The keybinds are all configured in `keys.lua`. I don't have any keybind to retrieve a minimized window but if you're using my rofi configuration, mod+W will give you a list of open windows including the minimized ones. 

As for the notification bell, I actually abandoned that functionality since my use case for it ended up being pretty small. The branch currently under development is `cyberpunk` which has a much more useful status bar. You can try to tweak things and see if you can fix the notification center but there probably aren't going to be any updates on that.

**Comment by fxrstor** [comment]
Alright. Amazing. I'm gonna try the cyperpunk branch. As for the issue, it's fixed. Hence, I'll close this issue here.
